service: serverless-typescript

frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

package:
  individually: true

plugins:
  - serverless-webpack

functions:
  worker:
    handler: src/worker.default
    events:
      - http:
          path: /
          method: get

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: 'npm'
    excludeFiles: src/**/*.test.js